apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wikijs-tls
  namespace: wikijs
spec:
  secretName: wikijs-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - wiki.thundertest.org
