apiVersion: v1
kind: ConfigMap
metadata:
  name: wikijs-config
  namespace: wikijs
data:
  TZ: "UTC"
  config.yml: |
    port: 3000
    db:
      type: sqlite
      storage: /wiki/data/db.sqlite
    logLevel: info
