apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  namespace: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: ghcr.io/requarks/wiki:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: wikijs-config
                  key: TZ
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: wikijs-data
              mountPath: /wiki/data
            - name: wikijs-config
              mountPath: /wiki/config.yml
              subPath: config.yml
      volumes:
        - name: wikijs-data
          persistentVolumeClaim:
            claimName: wikijs-data
        - name: wikijs-config
          configMap:
            name: wikijs-config
