apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - sealedsecret.yaml
  - postgres.yaml
  - pvc.yaml
  - wikijs.yaml
  - service.yaml
  - ingress.yaml
  - certificate-wikijs.yaml
