apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs-data
  namespace: wikijs
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
