apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs-data
  namespace: wikijs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-rwx
  resources:
    requests:
      storage: 10Gi
