apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs-pvc
  namespace: wikijs
spec:
  storageClassName: longhorn
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
