apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wikijs-postgres-secret
  namespace: wikijs
spec:
  encryptedData:
    password: AgDjoiqZwZJMIJXF1pfJ7Zod4bev9IN5cvSwVWHUatUBrbdHexkFz+y4aBLK0R1a25NmbUkgimy/5V+g0WrTC7/dOPTSFTRtVS9eDQ1bknOEWvVduYMafQdzqwN4D0GhJo6icFFvnNqm31AHPx6AnOWSdp80YsuXxv1AkBq62JAVgnd3iDsKCGxfkmD2JZdx9VvQkpiMpb38X0ZA5OGfUmz9BVwgXWbjgKYLlLsOCyy8whM8KPc3O8eAPyDVfm6cfzliCibe5WVXmjZhs9rLiBJ4yC53/6C4h3YwT4Ne9utXeVJCROn0UnmUsoSUuXMF/raKLNoWx3YrSamjNRFwGXrh+x6Hu1QjSOHMekY29u+wbO2viNpL/rmFIlqV3KYY587G8VtxX3gsYVPAwrtsI3dS8siAZ+QmG8amfMbb5Hcs+9xySPrr0LC5Hsn4SXfxwd8PaeC3yKmV3mWUPxRbfK9tFJceAlj5MukPPUQYu5MryZj7PbpeLEoyX8demE1FT8afSKw9IHk6bjlggy2CxsRhykoEJtxaO3vmBDjgFejGqluZzwmIsffhLgmFiSxjtGeoDMwR0oD64YGrpfEKYwIxkrAJEx7rk2lUUC33ZL3q65QV9oJdYJKb5Q/UpKj2mt7CGsQm7Uj7WbUzeTZ/5hHiCvfcg1WwbdFRnAbS71Xjk3qICvi0mF2F8K43EEQkfJRg4zLJJPScwz4=
  template:
    metadata:
      name: wikijs-postgres-secret
      namespace: wikijs
    type: Opaque
