apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wikijs-postgres-secret
  namespace: wikijs
spec:
  encryptedData:
    password: AgCvu7rdNnMt+oHBbj3niBMU3osdc8B4AA6Q49oiwqEmE9wX3Fr/pU6xkNraFCq/RA5lnbc2q5dkN3Y3D+U08DX0BQjmnijKkEeN1QGAMttXYOtEYcK5wEQHeqNjAbZWYCCfFg2NijDZTpfLoaY2h6ZGChMgpilaWgAoQV85wh/5RpZJfTSArIr7rTucr6EVLxkxdBSxSdYZX41fPJ54B9cdTikq1gkkx1Gx3MNr6D6s9p3Mx2nRXxn9MB2UWgclj8HgBR0/pCIoHHZ6Z7KURRM5Kmat1HqMgqnY8NZKjKDiEMfzwNg6fbtAkfirhdwCIzyinRZrS+Q7QlMY0mtUjrESqKwBD74snfV22WLH1etIdEZEcEXPL2uSFqPfwFy7x7xZK1Lv3TdJpt1au3VXn0OpiNKxMU+So6BJJ2jcBks7EI9a3GwFLqZ1sYIJ651R1XaPpTFC6NwdHm8cwyRarlGYbk7K3Kfkj7lwKxO6JpWJTz9RHfLEjI0F+M1RjX9k2ZuOXRLDEmm8rADkNGrZkF0PYqbjzbfOkPx0cpPLFDu5gQjILjaD4LwcZHmaF/vkuo3oVSf/9kHeWX9c84tB/MBpEuKwlkS5aEI1m5NKw0L0t5/4m/8JGXvuSnjhm/WFm218nklBJ/HL0qat6N/Vut0bUkFe2fKD4t09BqtarVKNvF2bdsw62uVUBmqIePUNy++/QZNii2pCbjo=
  template:
    metadata:
      name: wikijs-postgres-secret
      namespace: wikijs
    type: Opaque