apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wikijs-db-credentials
  namespace: wikijs
spec:
  encryptedData:
    POSTGRES_USER: CHANGE_ME
    POSTGRES_PASSWORD: CHANGE_ME
    POSTGRES_DB: CHANGE_ME
  template:
    metadata:
      name: wikijs-db-credentials
      namespace: wikijs
    type: Opaque
