apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCn9hDcnaFZqAj9GU3uGaRK8vdreep4n7aSIoRf364VwlxJt3cflsr3lB/svlY8D3XIQi4u37zL3+RPjXRr72tVxGp/e6ioBE37De48sqOxiJLWLW/I5bRL1g+XBGPV6PkquDuTzP5drTDsf0+Dc6Rlzg8LLDfJkIaY5j91IebVHz4T5rj5On1zuUuGuFxBwctFNXsLOIWJANmop2BMxslp8fGn3DVmjAQV9e0TeqZP3zInaiY0nJnXqIIZ/LozLA2iwYwFgsNvuag217COChOnC6abhL3din3pg/dnBBhCLqD9g8EDdWV1h8x/5B+S/kb5+L53PAAgmoBelZ60WP47MLoQcp7rXHKPl/50yuhCPBu9qpSMUDuhAM/Eu6PSMoFzfrZdvZcFGaVeohG6zzNFP3g5yDjV9EvA+DykpgbpvuTWhSZGhGldoo/+uHxESTE30BG5toSqN2f+xlbTOOF7+g2lbb0in8E6mFZUYysoyVlfmYpNWjXNr9cvNisgYD34ct5yYG6sEgDZShs0y7glAAqkEiCxREKedAXiCvZW2xukXVz4fbl2TlpG6CsLiOdYMhxRDMd8ideKwQDwpIuDgCSz6UBtIxKNO6EfRLaYLKr5yQdlC7f7DBLtU4r8XWnBxrs5GHdq7zSaLbbxptCeElRSCYWv9MC32wyhDRpUO5vHM1kmE6NqgM89C2p3Q7Irx4Eg2JBjuwvz3mRVXb3I5eSpFNrBbydsl5XyRGwXV+ccYUXMp2QG
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
