---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: awx-admin-password
  namespace: awx
spec:
  encryptedData:
    password: AgAXsca7DRBc01KR+uF73PMH7ibw4vl7DXyOhakcSplwpH5U/N79C3nO+DPVbw24AtZHWGPURKwPGEte35D7IjU4cnaKfucRegJ3/hCde02OqZi+KlchOHnKd1B77cTUI0nhy65xvo/Sht3hRRenccLuPByOieJXXTpSabmzpJ70yKMOb9m7jjLTweMn3hh/RODDc3xmaawwAVkh+q20ZkdURpsZSqw3/4bHmZ4TjVO4zILfaNoxOT2eBOUiMYGNxgsPQvhDY53zu1iCebQs7yXT+TIN1fzNGac/yEXGUEn0Uf+O7KvCWp3OpVnM5R10BDDeuTuEsW1uG4Yx2FDcp/4NyPh0VeSH5faRkCfErknjNPR8kpOoJJqfV44JiX5MSBMym5ta5rr5Aj1jPBHvUhzUCeW5i2ZpQCTC+ICrt59U5dYPs/xyZF9GShuBEsVx3Ph2CzO9EIbaPtZKYPH1H9Jy4GJNqW3i1k8sOTw21+MubvARgZxh4nHdn82M1QFmU/E3Uht8tyh94awHCn0mg5CbogCKPhK2//MBvomSDA7Z84SwkF6aq1+khn4x5azRUCq+KJlz2pjgYT4IPJZnpvX+3kYvq63+3gSKBjRYn03Sws0tSxWBV4KvMULZK04A70t5TUmC88SLpSAb6zwe4FAE/47v6fBD4pOPqU/6ablfRQjsDg76Lk5WjJbUSR+KUGomwmjNlpNivXc=
  template:
    metadata:
      name: awx-admin-password
      namespace: awx
    type: Opaque
