apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: awx-admin-password
  namespace: awx
spec:
  encryptedData:
    password: AgDFyv+nZU3rFrXJmNb0rHnnxVFbCyQA3eqEh0OiLYAu376BFUX316GCLhjr24isSK7jsWZmbaL6Ox4BEr4/GHSN7lR0MNcVh5HSi0P+j71PA4AUQdY41XzKf8giA3IhmBPRUjvP03X+DBpcBmFJDM2qSUObwfY2io2deC9JoMZnIip1DSvxShLuDQJWZSZuWVd+ht65uxjOh717puMy1OesH7v6xBVX5FVPXnBzl12QckcvoEoVY7Q8bc5AErhH1PPSwXB2+JQKxkdEkd8IDK4pZeOzlMsBddzxUDWCZzFS5Ms3DEcANEKXMaKpdeiGU+KxmEGi/SrfoVX8VOaj/V0ZFNBHz/ESJtVgbeO6XVYZ8yIVrjCOQDxLkJM+WZric8Z47ExBXZ6hRPVltMZl62wUHJ/+IMz+FGAuy4VFvqhh6GriHoNVBzrb8xjpDXTMS+P1rg7bGMBt7JxCCMqMOnZrn3H1PbrzV3OhjxY88LBF4NSQPIuvxsHvnM+EIsPrwwU4oWShT6s+vR8HkwZ90IExfsE/M20DSsncE/Ydzp06JYTJQSgMGebPP3+BgxUIVJgWdDPaRByPZD7gpSVo/idKcG4AswHdBSxm3cqOSBeEZkicCdEl7UJT8CceHGUVlfTaqaJuSn8fSC5x0X4RMN/RtCMlm/EFxzMC2cu1dPLp/qVAcXvxt4EN10D8tmvJ9lPr+/Ga1vq90gU=
  template:
    metadata:
      name: awx-admin-password
      namespace: awx
    type: Opaque