apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: awx-secret-key
  namespace: awx
spec:
  encryptedData:
    secret_key: AgAYKRhx8WCSo0P0Fcaz5d968ozLirtlpQkbP+8bM4azwdPZ6TUekThoX8seR+6nDK3ehBlg0JM09IP3xmYqglwUQ0PSxtzMIbkRqinhwh8vJjIAcLcDlFKu70gi5tXvdjHztruIaU8g/Iv/PhWSh1Aj4r2OcFIc+A1e3ZAzgk8JD/59imVLcw4RW9M30bOpH46XLqdcmIz+wMkePCkG1DHy8X9XMKsZtXgzhaKEKxOL1lMAFix7K3kQDUcog5CHiEwb7IX4AVYlC1hv/3e4iq0Su7d8j5Nlm7+bGUPLdcDubyhTBP4JsMNYpQimx8jhumsTojuwEYBQhoW89eiNo+BoggpT+uaklU6EAjYHx/6twxKlmYt/A1iPEudOyy+gdJIjgYpdNTWznihKhHrt0d3w4LMHCicH0PDQWbRuvg+r7YkhXssAbHX0O37mgEE3w/OIyCgL90xYdQG4Qn7u6ycpP2w2pGYFIy6uRCuAJNPH2ZQP/Khlm3bs9SKK315a65Ql40D5UDDcaItMETBDNKw3+VocXvg/F+qzjfO9ZEw2mqDZDmjhQSnaCNBvX/FgG9L3Nb7357QnLxfM5kdnupVjfti3Gcd7fCZS6x23CFHwCknDIGsB1Mcx78WXxKiYuJOmFyODdOpbm4jkNd1DlzgCBRt0K2gQsNEyy7qV0ih5Bsy3F2cA3K5BciBIvQygPH5R9OVKTLNVTPut1zZHDfrRHH/pyME1we5vuvrfMMoSng==
  template:
    metadata:
      name: awx-secret-key
      namespace: awx
    type: Opaque