---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: awx-secret-key
  namespace: awx
spec:
  encryptedData:
    secret_key: AgAWoIoUaPFNJz1je6bp16Ur/Z4XtUJ933atsCN1gmXopIHVnXMKv5m6+OEGAa2TrT/KdTCXF+FSXGvyPJ/fztJrTKBvn5tfYKdRPHbeNJ26WtvSYfLd+DArjplIsWhgFSC/JgBPIzhEOPknMFZ21JoCK06Fho/81Ixjaaqvu8EIBeEkzcOAypffJOCJISh4AaDyuFy36V+0rwx50aw50c+D7sW5q1LTMbZ/Qpc+qq7iyJanGQMh96kSYCgj0kQJoT9obkZoXhHGA3XuIAGeX6QIWyUQeRKp/VlV5B18gSSoFpvOAbcWSr9pud2LY3WDKKbxk+MPlr6JFbxo5DoC+M3jRhqKikhQC9Lk+AUVU0+zfDRlyWZhCZSdvgTwjctapd6PZowCxUz7vLENZMGJicEZ+H5tKbJ0OJwevZm4zN2dAJe62tK4z1FEMqkF8OunCN5l69/6fUwNubgNJQcqVBui/+zi6MSL1Szjccb1pUqW1cVjopfd5C6GElNal2zo4iWERbARdtzoqFoDjUsw2mD/1Pi3c5Z2HEARaCYRgHSEhp19KKvLM7H9Nmxgy6Gs867ynFIL0/EPPDmpWb++va1xeDJTnG9vKyb/SLljJmp7VD8Qt2W9QMAoGcaC87ZidfWcWUYiSa3Zy46ClLPT0BHj87b/KJz0C56eRzzUZv8yOsk1+Zrh4C0od/ZI4/5DuZZqS/hu6IP0YRTMydIm0dRXY2VRjO4wUW5i2i4nWq45Ug==
  template:
    metadata:
      name: awx-secret-key
      namespace: awx
    type: Opaque
