apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: ClusterIP

  admin_password_secret: awx-admin-password
  secret_key_secret: awx-secret-key

  postgres_configuration_secret: awx-postgres-configuration

  projects_persistence: true
  projects_storage_class: longhorn
  projects_storage_size: 10Gi

  ingress_type: ingress
  hostname: awx.thundertest.org
  ingress_annotations:
    kubernetes.io/ingress.class: nginx