apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: awx-tls
  namespace: awx
spec:
  secretName: awx-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - awx.thundertest.org