apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: awx
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: awx
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: awx-postgres-configuration, key: database } }
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: awx-postgres-configuration, key: username } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: awx-postgres-configuration, key: password } }
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data            
          readinessProbe:
            exec:
              command:
                - sh
                - -ec
                - pg_isready -h 127.0.0.1 -p 5432
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
                - sh
                - -ec
                - pg_isready -h 127.0.0.1 -p 5432
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6    
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 10Gi