apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: awx-secret-key
  namespace: awx
spec:
  encryptedData:
    secret_key: AgBr8kkQE/eL3DDmDyYbLF7MP4mO3T0MEY7zkiRNVQpvDfRYiAPuQmcLLASCcN1OcGYHH3KXpQnYjLfwdxNNjRIeNdJx+E8fNMFwvPgzWnEjO12XNYaXyIOb1mkhjgrUTYqoKk1ewStIus6R2JuajrZFRuJqZ3PLBuuwNfvIrkklGNL1Q4tlcTCbiXdRtUol8YvEO/9R9zoVu1rTZRzF/FQANslrJtaM8RMFwJ9w9d0B5qwZWp53KfLR5Fwae0/Hv/hR+YpgiGtnZQmxPlWwmcUaDUknH2SlforqS7at3BGMUtTxm24RC15DNyueIemHV0QpF5R2dvjL4sBZHby3l6ouYroTlCdR5NFeZDoSAsf7U15PLvr40TojSe5wS9PsA19YeM0yS2NwKpU14HQpClv2MyUXuQkR5YZ8Vj+hkWZXpxPM8kz8tEnx31P9li0f3gi5odGXN+IgPFY7NBmW7uAlGyLIkTClbJ2TNsTfV3ld8vuwpnLvVvS+a2CEPtIgNbgUewqMUNFunioioGDCdePNY1sfHhHWMYCRDdsFLVsaxInmsV9/SuVgEwT0yh2eLayXyMkfHp+G6F0/ehsR2e+yvT7LEjh8xioMIMaf6gURNZqBE8Nm5QoG+B08rFgKgNgEqk7201bEBxwlZMVRR7eyn7MwPIqkINbVw4DzYkfhpBxz5p08EOzEakczXbFSU7gXJqZyHeX5DZQwgs4WGtBbOfW9WFcUmIl/LHK68i5IlA==
  template:
    metadata:
      name: awx-secret-key
      namespace: awx
    type: Opaque