apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: bazarr
      containers:
        - name: bazarr
          image: ghcr.io/linuxserver/bazarr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6767
              name: http
          envFrom:
            - configMapRef:
                name: bazarr-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: bazarr-config
              mountPath: /config
            - name: media-tv
              mountPath: /tv
            - name: media-movies
              mountPath: /movies
      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-config
        - name: media-tv
          persistentVolumeClaim:
            claimName: media-tv
        - name: media-movies
          persistentVolumeClaim:
            claimName: media-movies
