apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-tls
  namespace: media
spec:
  secretName: jellyfin-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - jellyfin.thundertest.org
