apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lidarr-tls
  namespace: media
spec:
  secretName: lidarr-tls
  issuerRef:
    name: letsencrypt-cloudflare-prod
    kind: ClusterIssuer
  dnsNames:
    - lidarr.thundertest.org
