apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: lidarr
      containers:
        - name: lidarr
          image: ghcr.io/linuxserver/lidarr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8686
              name: http
          envFrom:
            - configMapRef:
                name: lidarr-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: lidarr-config
              mountPath: /config
            - name: media-music
              mountPath: /music
            - name: media-downloads
              mountPath: /downloads
      volumes:
        - name: lidarr-config
          persistentVolumeClaim:
            claimName: lidarr-config
        - name: media-music
          persistentVolumeClaim:
            claimName: media-music
        - name: media-downloads
          persistentVolumeClaim:
            claimName: media-downloads
