apiVersion: v1
kind: ConfigMap
metadata:
  name: plex-config
  namespace: media
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "America/Chicago"
  VERSION: "docker"
  PLEX_CLAIM: "claim-Y8fHrBHcqkLFtd7fv83x"
  ADVERTISE_IP: "https://plex.thundertest.org:443"
