apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-tls
  namespace: media
spec:
  secretName: prowlarr-tls
  issuerRef:
    name: letsencrypt-cloudflare-prod
    kind: ClusterIssuer
  dnsNames:
    - prowlarr.thundertest.org
