# Configuration - Sonarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi

# # Configuration - Radarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi

# Configuration - Lidarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi

# # Configuration - Bazarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

# Configuration - Prowlarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

# Configuration - SABnzbd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi

# # Configuration - Jellyfin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi

# # Configuration - Plex
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi

# Configuration - Navidrome
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi


# Downloads NFS Storage
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: media-downloads
#   namespace: media
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: nfs-dev
#   resources:
#     requests:
#       storage: 500Gi

apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-downloads-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 10.11.11.48
    path: /srv/vault/downloads

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  volumeName: media-downloads-pv
  resources:
    requests:
      storage: 500Gi

# TV Shows NFS Storage
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: media-tv
#   namespace: media
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: nfs-dev
#   resources:
#     requests:
#       storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-tv-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 10.11.11.48
    path: /srv/vault/tv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-tv
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  volumeName: media-tv-pv
  resources:
    requests:
      storage: 1000Gi

# Movies NFS Storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-movies-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 10.11.11.48
    path: /srv/vault/movies

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-movies
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  volumeName: media-movies-pv
  resources:
    requests:
      storage: 1000Gi

# Music NFS Storage
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: media-music
#   namespace: media
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: nfs-dev
#   resources:
#     requests:
#       storage: 500Gi
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-music-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 10.11.11.48
    path: /srv/vault/music

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-music
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  volumeName: media-music-pv
  resources:
    requests:
      storage: 500Gi

# Configuration - Stash
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi

# Configuration - Whisparr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisparr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

# Adult Content NFS Storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dirt-content
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-dev
  resources:
    requests:
      storage: 100Gi

# Downloads NFS Storage (dirt)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dirt-downloads
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-dev
  resources:
    requests:
      storage: 50Gi
