apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sabnzbd-credentials
  namespace: media
spec:
  encryptedData:
    SABNZBD_PASS: AgDXPVNPr601zb+MHMI5N7YphxKWkxZwWx72+FNABZrM88FUw34Ab7LWsexrgaR03gUHDtyPW1G8OdSYRfpiPmPwJGEZ2ZbewzghiIper6LoTYP40QW86snfQZhNrjmlLHzcvLVeuG0byqAMvN3tZ3+q+khqVfUlsT16dZHBoHSuKMmsdh4Wmxi36M2tqqpPmLeFrDIfj0KiaYIYJxolEUJujeTqvdECk0txmKgD6UxD/ABYYmZFNPbRj7i09PWds+nr6V2G0NvpumT/n7cekHBUWIxkWCQCF24HrpdRtkLCPAgFF1e595IfmEg4Ipswonz5LxguFudq1ATyzYQYS5B9IP82PlPaZM0hAhOeFzOYiJ6HRip/0r/AshAmLdg23Gw/zzccKjCBKBvxiZRZKO7OesLSuLc3fgINrCpjC66qz0I6N6yLEYR1r+Ahlg0vetFiYOnNG0zJey/S1rekV6MLo6mAzhDbDITHEJoWzDa1j3E4XVgqYJhxQHo3HTfeGVzZxzfq5RNU2Ro+f0FWgdo9Q841bv09IkDqi83vCy8a8qbJWEtT07VFQ0ByUp9g+nQ7laMC6yCAPqRMX2P6zK3pvFPrtcZwZgoHXczEi/A/MtGBMTBZXohR/pCoPSCi2m98flTWL5+r1Wvi/0rOl8mMnv+0MZGlCbqBgZmK2ZhG8W2mYYj6geUsxI65enSlgxDJOMuE+DDkxAk=
    SABNZBD_USER: AgA83eVmKVU7c7MW5xziaTkxm4aYZ/wZ6Y21ylOi9PoJ7ajb1iJybDwLH+oPlBAwYlIG1zWzL/G80prXKvG2+TeVOQEI3xm5JeGz1+wYv0gWtlHpw+jJmKpDgo+sC1NV5qs4XcwCBRgxc0xGpBLoXcBsrC3LfhUADkNOlk8QQTteNxQgYtc1a3Zd8CBD+ldAgkrLinRwKTLv3Z2AqnwbiimtWnm3OeMfJLxztKP0FQUV4f0lZ0fhE65x3uW1rX9cp/WHkAl98r+u6ND20yBsQIelZdVMMvnw87g2Ijd3UIXXTNY0jxDAC8YMv/9luLxu4L5cM2ouckWRz1VAqoz6D3zGE1Ffn/9Dk0WJ1tFZ2hq5DsKhUxUG2yOZTjPLwu1Z72T1lUMn0r930mXFJcyEyLVEIaY9WXt9HBjo8Zd7+qVNm0SVa5HMwer9FYY0FQ2JWuXo83R5Fm1gZSq418dpoCCI+FkPpXfiB+V3YJztHSAuZtrwQGG/uTBJhUosEHOoV4J/aTX5Zty1/C8EPGKV7Pev7xyltxkc62VMRKJ6rGrXIzO3AlREIpbCAu2PYyuKspGLw3VRtZOt4jIi1nuU42o0PovzEo1yM2iJF300OZ3z8SmtMbrNwHM2crTZXW9ROh1PPeERFPBrRUuW2LI0oi2JQugjvbqMk2H0kUYZqYmQYSuonM/xUUzGQ1lLkWAKIujhvBAr6g==
  template:
    metadata:
      name: sabnzbd-credentials
      namespace: media
    type: Opaque
