apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: ghcr.io/linuxserver/sonarr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8989
              name: http
          envFrom:
            - configMapRef:
                name: sonarr-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: media-tv
              mountPath: /tv
            - name: media-downloads
              mountPath: /downloads
            - name: media-movies
              mountPath: /movies
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: media-tv
          persistentVolumeClaim:
            claimName: media-tv
        - name: media-downloads
          persistentVolumeClaim:
            claimName: media-downloads
        - name: media-movies
          persistentVolumeClaim:
            claimName: media-movies
