apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whisparr-tls
  namespace: media
spec:
  secretName: whisparr-tls
  issuerRef:
    name: letsencrypt-cloudflare-prod
    kind: ClusterIssuer
  dnsNames:
    - whisparr.thundertest.org
