apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie
  namespace: mealie
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mealie.thundertest.org
      secretName: mealie-tls
  rules:
    - host: mealie.thundertest.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mealie
                port:
                  number: 80
