apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

bases:
  - ../base

patchesStrategicMerge:
  - sonarr-replicas.yaml
  - radarr-replicas.yaml
  - lidarr-replicas.yaml
  - bazarr-replicas.yaml
  - prowlarr-replicas.yaml
