apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

bases:
  - ../../base

patches:
  - path: sonarr-replicas.yaml
    target:
      kind: Deployment
      name: sonarr
  - path: radarr-replicas.yaml
    target:
      kind: Deployment
      name: radarr
  - path: lidarr-replicas.yaml
    target:
      kind: Deployment
      name: lidarr
  - path: bazarr-replicas.yaml
    target:
      kind: Deployment
      name: bazarr
  - path: prowlarr-replicas.yaml
    target:
      kind: Deployment
      name: prowlarr
  - path: plex-replicas.yaml
    target:
      kind: Deployment
      name: plex
  - path: sabnzbd-replicas.yaml
    target:
      kind: Deployment
      name: sabnzbd
