vault2_devices:
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde

vault2_vg: vg_vault2
vault2_lv: lv_vault2

# Use 100% of free space
vault2_lv_size: "100%FREE"

vault2_mountpoint: /srv/vault2

# xfs is great for large storage; ext4 is fine too
vault2_fstype: xfs