apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thundertest-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: thundertest-root-ca
  secretName: thundertest-root-ca
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: thundertest-ca
spec:
  ca:
    secretName: thundertest-root-ca
    # secret lives in cert-manager namespace (where cert-manager runs)