apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-tls
  namespace: registry
spec:
  secretName: registry-tls
  issuerRef:
    name: thundertest-ca
    kind: ClusterIssuer
  dnsNames:
    - registry.thundertest.org