apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-tls
  namespace: n8n
spec:
  secretName: n8n-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - n8n.thundertest.org