apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sabnzbd-tls
  namespace: sabnzbd
spec:
  secretName: sabnzbd-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - sabnzbd.thundertest.org