apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-pvc
  namespace: sabnzbd
spec:
  storageClassName: longhorn
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-nfs
  namespace: sabnzbd
spec:
  storageClassName: nfs-rwx
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 100Gi