apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-tls
spec:
  secretName: homepage-dev-tls
  issuerRef:
    name: letsencrypt-cloudflare-prod
    kind: ClusterIssuer
  dnsNames:
    - homepage-dev.thundertest.org
