apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: docs

resources:
  - namespace.yaml
  - pvc.yaml
  - wikijs-sealedsecrets.yaml
  - wikijs-configmap.yaml
  - wikijs-postgres.yaml
  - wikijs-deployment.yaml
  - wikijs-service.yaml
  - wikijs-certificate.yaml
  - wikijs-ingress.yaml
  - paperless-sealedsecrets.yaml
  - paperless-configmap.yaml
  - paperless-postgres.yaml
  - paperless-redis.yaml
  - paperless-deployment.yaml
  - paperless-service.yaml
  - paperless-certificate.yaml
  - paperless-ingress.yaml

commonLabels:
  app.kubernetes.io/name: docs
