apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
  namespace: docs
data:
  PAPERLESS_REDIS: "redis://paperless-redis:6379"
  PAPERLESS_DBHOST: "paperless-postgres"
  PAPERLESS_DBPORT: "5432"
  PAPERLESS_DBNAME: "paperless"
  PAPERLESS_DBUSER: "paperless"
  PAPERLESS_URL: "https://paperless.thundertest.org"
  PAPERLESS_TIME_ZONE: "America/Chicago"
  PAPERLESS_OCR_LANGUAGE: "eng"
  PAPERLESS_CONSUMPTION_DIR: "/consume"
  PAPERLESS_DATA_DIR: "/data"
  PAPERLESS_MEDIA_ROOT: "/media"
  PAPERLESS_EXPORT_DIR: "/export"
