apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wikijs-postgres-secret
  namespace: docs
spec:
  encryptedData:
    password: AgDfLVLn0HTasYyaNVF19qkglJChicCwFDX8P7uns924oXpiotHVVSZjHp/5RRkrEKF2Q3VJnfYt9TwDuB1vZMs1iUuAzq1VLTKCWzPFP1MbmIk4Km8MKI6V94PnX2ilv0WP+ZnqyFg0AVvFFwSQleTMLex/qDckNpUxfokqPRswAn3ObUBzRHZbNToFzVtJqPvEUvs7NLxaBO57mI4+07zEpF+Xxz7O+y3zgM6ubzny0TBHnQxpsrX8aHoEgSJ5w3a/zvB43S2fQiIyGCWbQ9Xd4bSHJk80SHq7nUhEZp6B5TtF6PpXSiUqeIk3RZ//CRK+XMUOZj15NlfGUbh3SPwL89bPfCjGottjKDuQwbnSeGfPyufCPXFoTD0ImWw9Pz8/Y/t3lmWsRhrRT6Yu3U/V3yEB2diezXdExxv1ix9H6ts8o9SWAcciFZTQfXcP46Z7LqsFljjvpr7XWr1DrR6ngEyNzgnKE1oH1YiSP3lIHLDaJkQt5ZNpBtcjDfFZKO7QCgD8V8gsO3REsSIPNDwjzJp7z+XUu7LEC7dz6QRALUBfhnHtsffR12dJkcRxWewjF6Y+CNOpaSoV0GngacOy6JQSuOeP6/Phz9EgOazetZP+qmKfbhe+TBfJ0rgnsJi0ZtAfQEe7k5JL0lHnuChm3olZ0kGpGc+WvQQuR7zSIJ/VxQxogPF2juF1TPlqaZeKAKLVbUJVf2s=
  template:
    metadata:
      name: wikijs-postgres-secret
      namespace: docs
    type: Opaque
