apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  namespace: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: ghcr.io/requarks/wiki:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: wikijs-config
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: wikijs-postgres-secret
                  key: password
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: wikijs-data
              mountPath: /wiki/data
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: wikijs-data
          persistentVolumeClaim:
            claimName: wikijs-data
