apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/mread998/ThunderLemon.git
    targetRevision: Development
    path: homelab-gitops/apps/awx/overlays/dev
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: awx-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
