apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mread998/ThunderLemon.git
    targetRevision: main
    path: homelab-gitops/apps/awx/overlays/prod
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: awx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"