apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://ansible-community.github.io/awx-operator-helm/
    chart: awx-operator
    targetRevision: 3.2.0
    helm:
      values: |
        # Keep defaults for now
        # (We manage the AWX instance separately in the next app)
  destination:
    server: https://kubernetes.default.svc
    namespace: awx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true