apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.longhorn.io/
    chart: longhorn
    targetRevision: v1.11.0
    helm:
      values: |
        defaultSettings:
          defaultReplicaCount: 1
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 1
        preUpgradeChecker:
          jobEnabled: false
        ingress:
          enabled: true
          ingressClassName: nginx
          host: longhorn.thundertest.org
          tls: true
          tlsSecret: longhorn-tls
          annotations:
            cert-manager.io/cluster-issuer: selfsigned
