apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mread998/ThunderLemon.git
    targetRevision: main
    path: homelab-gitops/apps/sabnzbd/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: sabnzbd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true