apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-tls
  namespace: homepage
spec:
  secretName: homepage-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - homepage.thundertest.org