apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: "Homelab"
    theme: dark
    headerStyle: clean
  custom.css: ""
  custom.js: ""
  proxmox.yaml: ""
  bookmarks.yaml: |
    - Dev:
        - GitHub:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Infrastructure:
        - ArgoCD:
            href: https://argocd.thundertest.org
            description: GitOps controller
        - Longhorn:
            href: https://longhorn.thundertest.org
            description: Longhorn for storage management
        - AWX:
            href: https://awx.thundertest.org
            description: Ansible AWX for automation
        - Proxmox:
            href: https://10.11.11.48:8006
            description: Proxmox VE for virtualization
        - HomeGuard:
            href: https://10.11.11.25
            description: HomeGuard for home automation

    - Media Services:
        - Plex: 
            href: https://app.plex.tv/desktop/#!/
            description: Plex for media streaming
        - Jellyfin:
            href: http://jellyfin.thundertest.org/
            description: Jellyfin for media streaming
        - Sonarr:
            href: http://sonarr.thundertest.org/
            description: Sonarr for TV show management
        - Radarr:
            href: http://radarr.thundertest.org/
            description: Radarr for movie management
        - Lidarr:
            href: http://lidarr.thundertest.org/
            description: Lidarr for music management
        - Bazarr:
            href: http://bazarr.thundertest.org/
            description: Bazarr for subtitle management
        - Stashapp:
            href: http://stashapp.thundertest.org/
            description: Stashapp for adult content management
        - Whisparr:
            href: http://whisparr.thundertest.org/



    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /
  docker.yaml: ""