# Dev-namespace SealedSecret patch for awx-secret-key
#
# REPLACE the encryptedData.secret_key value below with the output from kubeseal.
# See secrets.template.yaml for the full workflow.
#
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: awx-secret-key
  namespace: awx-dev
spec:
  encryptedData:
    secret_key: AgAmOecD0QhYfE09pJJagc0A7CbMMTT/SZBPWMFxjIF0pfwyrbrAafI2C+bY3m5+7BGSpInOF5a22a4kZZI9UAupNIBY2YiyjR7sbxmLWbIVopgM20+3tBCiJPEJq2iFIQLH7YpD8TX5SMZ1KulPKu8j1/rHq9EbxeAV1DBjmbRavIvAjoyNHZNOH5YRBSqEpyHrQPcP/axIF9umDBxV7GONKhAbnXUai56hjNdyGT8p7U1CeSxy9yo/YmsOJnY+HhJ0SrvmKysZCWJveq9NA27pghNoHsl65olU5xdqvXbW6qFMge7pRZzO1wcnVT0D+CmGnVP6p+a4dojurJ9EwhDZhVhwzGR5fyyBIXrR+GiyhoVQCrRpoPXZu+5AZCs1nNRjf5BDU/CSYSznL7x8Yf1IhIU206aP36xB9XoXqZwLLrfa1ckbLUG3QMHt7E4oJVEwTSy8arP6UOr6o+r+mkBYAoCsgbSOyBMu1TjGhYl7M2JuKo6EnZTRFdx54XVg7mT2p0rnEZ1Q2oaE6acJPYLwjNg+NqWeJTObYdKC1bhSA0TwgFiWhSSGg0/QoYXv0N8iXoMmWhmFutWuGZbX6Wx5UdDx4kFEinvBpF9Z+jA0danW2H9pLPryDXpAVoJ1+jpyvQHMoS8KhlUaO0iH5FanQZlgwlLLJNjEMGaE3YnRI7pnyvmhba6cHUxqmUWpfU9Q3OPbG6G7fcTWJo6fc7aHq4yJsRBsDVY1MtZQ
  template:
    metadata:
      name: awx-secret-key
      namespace: awx-dev
    type: Opaque