apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: awx
spec:
  volumeClaimTemplates:
    - metadata:
        name: pgdata
        annotations:
          # Use 1 replica in dev — faster scheduling, less overhead
          volume.longhorn.io/number-of-replicas: "1"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: longhorn
